// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menu-explore-collection'
  | 'menu-explore-items'
  | 'menu-open-workbench';
