// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "providers": string;
      "budget.maxRequests": number;
      "budget.maxOutputTokens": number;
      "debug.verbose": boolean;
    };
  }
}
